"""CLI command: tldr - Quick project overview."""

from hyprwall.cli.cli_common import (
    print_banner,
    print_header,
    print_separator,
    Colors,
)


def run(args):
    """Execute the 'tldr' command."""
    print_banner()
    print()

    print_header("What is HyprWall?")
    print(f"{Colors.BRIGHT_WHITE}HyprWall{Colors.RESET} is a {Colors.BRIGHT_CYAN}lightweight wallpaper manager{Colors.RESET} for Hyprland.")
    print(f"Set {Colors.BRIGHT_MAGENTA}images{Colors.RESET} or {Colors.BRIGHT_MAGENTA}animated videos{Colors.RESET} as your desktop background.")
    print()

    print_header("Why HyprWall?")
    print(f"{Colors.CYAN}▸{Colors.RESET} {Colors.BOLD}Wayland-native{Colors.RESET} {Colors.DIM}— Built for Hyprland, no X11 legacy{Colors.RESET}")
    print(f"{Colors.CYAN}▸{Colors.RESET} {Colors.BOLD}Smart optimization{Colors.RESET} {Colors.DIM}— Auto-encode videos for battery efficiency{Colors.RESET}")
    print(f"{Colors.CYAN}▸{Colors.RESET} {Colors.BOLD}Power-aware{Colors.RESET} {Colors.DIM}— Automatically adjust quality based on AC/battery state{Colors.RESET}")
    print(f"{Colors.CYAN}▸{Colors.RESET} {Colors.BOLD}Intelligent caching{Colors.RESET} {Colors.DIM}— Never re-encode the same file twice{Colors.RESET}")
    print(f"{Colors.CYAN}▸{Colors.RESET} {Colors.BOLD}Multi-monitor ready{Colors.RESET} {Colors.DIM}— Detects your displays automatically{Colors.RESET}")
    print(f"{Colors.CYAN}▸{Colors.RESET} {Colors.BOLD}CLI-first design{Colors.RESET} {Colors.DIM}— No bloat, pure terminal efficiency{Colors.RESET}")
    print()

    print_header("Quick Start")
    print(f"{Colors.BRIGHT_GREEN}# Set an image wallpaper{Colors.RESET}")
    print(f"{Colors.DIM}${Colors.RESET} hyprwall set ~/Pictures/sunset.jpg")
    print()
    print(f"{Colors.BRIGHT_GREEN}# Set a video wallpaper (auto-optimized){Colors.RESET}")
    print(f"{Colors.DIM}${Colors.RESET} hyprwall set ~/Videos/ocean-waves.mp4")
    print()
    print(f"{Colors.BRIGHT_GREEN}# Use a directory (picks most recent file){Colors.RESET}")
    print(f"{Colors.DIM}${Colors.RESET} hyprwall set ~/Wallpapers/")
    print()

    print_header("Rendering Modes")
    print(f"{Colors.BRIGHT_YELLOW}cover{Colors.RESET}   {Colors.DIM}→{Colors.RESET}  Fill screen, crop edges {Colors.DIM}(default for images){Colors.RESET}")
    print(f"{Colors.BRIGHT_YELLOW}fit{Colors.RESET}     {Colors.DIM}→{Colors.RESET}  Letterbox, keep aspect ratio {Colors.DIM}(default for videos){Colors.RESET}")
    print(f"{Colors.BRIGHT_YELLOW}stretch{Colors.RESET} {Colors.DIM}→{Colors.RESET}  Fill completely, may distort")
    print()
    print(f"{Colors.DIM}Example:{Colors.RESET} hyprwall set --mode fit wallpaper.jpg")
    print()

    print_header("Optimization Profiles")
    print(f"{Colors.BRIGHT_GREEN}eco{Colors.RESET}      {Colors.DIM}→{Colors.RESET}  24fps, Quality 28 {Colors.DIM}(lowest battery usage){Colors.RESET}")
    print(f"{Colors.BRIGHT_CYAN}balanced{Colors.RESET} {Colors.DIM}→{Colors.RESET}  30fps, Quality 24 {Colors.DIM}(recommended){Colors.RESET}")
    print(f"{Colors.BRIGHT_MAGENTA}quality{Colors.RESET}  {Colors.DIM}→{Colors.RESET}  30fps, Quality 20 {Colors.DIM}(best visual quality){Colors.RESET}")
    print(f"{Colors.DIM}off{Colors.RESET}      {Colors.DIM}→{Colors.RESET}  No optimization, use source directly")
    print()
    print(f"{Colors.DIM}Example:{Colors.RESET} hyprwall set --profile eco video.mp4")
    print()

    print_header("Video Codecs")
    print(f"{Colors.BRIGHT_YELLOW}h264{Colors.RESET} {Colors.DIM}→{Colors.RESET}  H.264/AVC, outputs MP4 {Colors.DIM}(widely compatible, default){Colors.RESET}")
    print(f"{Colors.BRIGHT_YELLOW}av1{Colors.RESET}  {Colors.DIM}→{Colors.RESET}  AV1, outputs MKV {Colors.DIM}(modern, efficient, VAAPI only){Colors.RESET}")
    print(f"{Colors.BRIGHT_YELLOW}vp9{Colors.RESET}  {Colors.DIM}→{Colors.RESET}  VP9, outputs WebM {Colors.DIM}(open format, CPU only){Colors.RESET}")
    print()
    print(f"{Colors.DIM}Example:{Colors.RESET} hyprwall set --codec av1 video.mp4")
    print()

    print_header("Hardware Encoding")
    print(f"{Colors.BRIGHT_YELLOW}auto{Colors.RESET}   {Colors.DIM}→{Colors.RESET}  Smart selection based on codec {Colors.DIM}(recommended){Colors.RESET}")
    print(f"{Colors.BRIGHT_YELLOW}nvenc{Colors.RESET}  {Colors.DIM}→{Colors.RESET}  NVIDIA GPU encoding {Colors.DIM}(H.264 only, strict){Colors.RESET}")
    print(f"{Colors.BRIGHT_YELLOW}vaapi{Colors.RESET}  {Colors.DIM}→{Colors.RESET}  Intel/AMD GPU encoding {Colors.DIM}(AV1 only, strict){Colors.RESET}")
    print(f"{Colors.BRIGHT_YELLOW}cpu{Colors.RESET}    {Colors.DIM}→{Colors.RESET}  Software encoding {Colors.DIM}(libx264/libvpx-vp9){Colors.RESET}")
    print()
    print(f"{Colors.DIM}Example:{Colors.RESET} hyprwall set --codec h264 --encoder nvenc video.mp4")
    print()

    print_header("Codec/Encoder Compatibility")
    print(f"{Colors.BRIGHT_CYAN}H.264{Colors.RESET}  {Colors.DIM}→{Colors.RESET}  CPU, NVENC {Colors.DIM}(no VAAPI on AMD Radeon 780M){Colors.RESET}")
    print(f"{Colors.BRIGHT_CYAN}AV1{Colors.RESET}    {Colors.DIM}→{Colors.RESET}  VAAPI only {Colors.DIM}(hardware accelerated){Colors.RESET}")
    print(f"{Colors.BRIGHT_CYAN}VP9{Colors.RESET}    {Colors.DIM}→{Colors.RESET}  CPU only")
    print()

    print_header("Auto Power Management")
    print(f"{Colors.BRIGHT_GREEN}# Enable auto power switching{Colors.RESET}")
    print(f"{Colors.DIM}${Colors.RESET} hyprwall set video.mp4 --auto-power")
    print()
    print(f"{Colors.BRIGHT_GREEN}# Run the auto daemon (monitors battery/AC state){Colors.RESET}")
    print(f"{Colors.DIM}${Colors.RESET} hyprwall auto")
    print()
    print(f"{Colors.BRIGHT_GREEN}# Check auto power status{Colors.RESET}")
    print(f"{Colors.DIM}${Colors.RESET} hyprwall auto --status")
    print()
    print(f"{Colors.BRIGHT_GREEN}# Run one evaluation cycle (no daemon loop){Colors.RESET}")
    print(f"{Colors.DIM}${Colors.RESET} hyprwall auto --once")
    print()

    print_header("Manual Profile Override")
    print(f"{Colors.BRIGHT_GREEN}# Manually set a specific profile (disables auto){Colors.RESET}")
    print(f"{Colors.DIM}${Colors.RESET} hyprwall profile set eco")
    print()
    print(f"{Colors.BRIGHT_GREEN}# Clear override and resume automatic switching{Colors.RESET}")
    print(f"{Colors.DIM}${Colors.RESET} hyprwall profile auto")
    print()

    print_header("Other Commands")
    print(f"{Colors.CYAN}hyprwall status{Colors.RESET}       {Colors.DIM}→{Colors.RESET}  Show current wallpaper info")
    print(f"{Colors.CYAN}hyprwall stop{Colors.RESET}         {Colors.DIM}→{Colors.RESET}  Stop the current wallpaper")
    print(f"{Colors.CYAN}hyprwall cache size{Colors.RESET}   {Colors.DIM}→{Colors.RESET}  Display cache statistics")
    print(f"{Colors.CYAN}hyprwall cache clear{Colors.RESET}  {Colors.DIM}→{Colors.RESET}  Delete all cached files")
    print()

    print_header("Supported Formats")
    print(f"{Colors.BRIGHT_MAGENTA}Images{Colors.RESET}  {Colors.DIM}→{Colors.RESET}  JPG, PNG, GIF, WebP")
    print(f"{Colors.BRIGHT_MAGENTA}Videos{Colors.RESET}  {Colors.DIM}→{Colors.RESET}  MP4, MKV, WebM, AVI, MOV")
    print()

    print_header("Systemd Integration")
    print(f"{Colors.BRIGHT_GREEN}# Run auto daemon as a systemd user service{Colors.RESET}")
    print(f"{Colors.DIM}${Colors.RESET} systemctl --user enable --now hyprwall-auto.service")
    print()
    print(f"{Colors.BRIGHT_GREEN}# View daemon logs{Colors.RESET}")
    print(f"{Colors.DIM}${Colors.RESET} journalctl --user -u hyprwall-auto -f")
    print()
    print(f"{Colors.BRIGHT_GREEN}# Stop the daemon{Colors.RESET}")
    print(f"{Colors.DIM}${Colors.RESET} systemctl --user stop hyprwall-auto.service")
    print()

    print_header("Under the Hood")
    print(f"{Colors.CYAN}▸{Colors.RESET} Built on {Colors.BRIGHT_WHITE}mpvpaper{Colors.RESET} {Colors.DIM}(the video wallpaper backend){Colors.RESET}")
    print(f"{Colors.CYAN}▸{Colors.RESET} Uses {Colors.BRIGHT_WHITE}ffmpeg{Colors.RESET} {Colors.DIM}for smart video optimization{Colors.RESET}")
    print(f"{Colors.CYAN}▸{Colors.RESET} Talks to {Colors.BRIGHT_WHITE}hyprctl{Colors.RESET} {Colors.DIM}for monitor detection{Colors.RESET}")
    print(f"{Colors.CYAN}▸{Colors.RESET} XDG-compliant {Colors.DIM}(~/.cache/hyprwall, ~/.config/hyprwall){Colors.RESET}")
    print()

    print_header("Philosophy")
    print(f"{Colors.BRIGHT_CYAN}Predictable{Colors.RESET} {Colors.DIM}— Clean process management, deterministic behavior{Colors.RESET}")
    print(f"{Colors.BRIGHT_CYAN}Performant{Colors.RESET}  {Colors.DIM}— Minimal CPU/battery usage, laptop-friendly{Colors.RESET}")
    print(f"{Colors.BRIGHT_CYAN}Simple{Colors.RESET}      {Colors.DIM}— No GUI bloat, just CLI efficiency{Colors.RESET}")
    print()

    print_separator("═", 60)
    print(f"{Colors.DIM}Project:{Colors.RESET} {Colors.BRIGHT_CYAN}https://github.com/TheOnlyChou/hyprwall{Colors.RESET}")
    print(f"{Colors.DIM}License:{Colors.RESET} {Colors.BRIGHT_WHITE}MIT{Colors.RESET}")
    print_separator("═", 60)
    print()